version: '3.8'

services:
    app_adminer:
        container_name: app_adminer
        image: adminer
        restart: always
        ports:
            - "8080:8080"
    app_db:
        container_name: app_db
        image: mariadb:10.4.32
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: motiongymdb
            MYSQL_USER: appuser
            MYSQL_PASSWORD: appuserpassword
            MYSQL_ROOT_PASSWORD: appuserpassword
        ports:
            - "3388:3306"
#        volumes:
#            - app_db_data:/var/lib/mysql

volumes:
    app_db_data:
